### ISSUE TITLE
RefreshControl

### ISSUE THREAD

**Issue by manuhook** [janicduplessis/collapsible-navbar#6]
Hi @janicduplessis,

Thanks a lot for this UI pattern, it's very usefull !

Juste one thing ; when i'm adding a RefreshControl to the AnimatedListView, the navbar is not collapsible anymore on Android only and I can't figure why (everything is working fine on IOS).
I saw you manage to handle it on the Th3rdwave app, can you give me an hint to make it work ?

Thanks a lot !

**Comment by Bonobomagno** [comment]
update:
this one is working both on ios and android
[snack link](https://snack.expo.io/BJqdcLS17)
